const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('petAPI', {
  getAssets: () => ipcRenderer.invoke('get-assets'),
  getWindowPos: () => ipcRenderer.invoke('get-window-pos'),
  setWindowPos: (x, y) => ipcRenderer.send('set-window-pos', x, y),
  onReloadAssets: (cb) => ipcRenderer.on('reload-assets', cb),
  openManager: () => ipcRenderer.send('open-manager'),
  getScale: () => ipcRenderer.invoke('get-scale'),
  zoomPet: (delta) => ipcRenderer.send('zoom-pet', delta),
  onSetScale: (cb) => ipcRenderer.on('set-scale', cb),
  onClipMap: (cb) => ipcRenderer.on('clip-map', cb),
  onAudioVolumes: (cb) => ipcRenderer.on('audio-volumes', cb),
  onHiddenImages: (cb) => ipcRenderer.on('hidden-images', cb),
  getMuted: () => ipcRenderer.invoke('get-muted'),
  onSetMuted: (cb) => ipcRenderer.on('set-muted', cb),
  // 环形右键菜单
  openRadial: () => ipcRenderer.send('open-radial'),
  closeRadial: () => ipcRenderer.send('close-radial'),
  getMenuState: () => ipcRenderer.invoke('get-menu-state'),
  toggleMute: () => ipcRenderer.invoke('toggle-mute'),
  setPlayMode: (mode) => ipcRenderer.invoke('set-play-mode', mode),
  onSetPlayMode: (cb) => ipcRenderer.on('set-play-mode', cb),
  toggleAutoLaunch: () => ipcRenderer.invoke('toggle-auto-launch'),
  toggleRememberPos: () => ipcRenderer.invoke('toggle-remember-pos'),
  resetSize: () => ipcRenderer.send('reset-size'),
  setDefaultSize: () => ipcRenderer.send('set-default-size'),
  quitApp: () => ipcRenderer.send('quit-app'),
});

contextBridge.exposeInMainWorld('managerAPI', {
  getUserDir: () => ipcRenderer.invoke('get-user-dir'),
  chooseUserDir: () => ipcRenderer.invoke('choose-user-dir'),
  resetUserDir: () => ipcRenderer.invoke('reset-user-dir'),
  openUserDir: () => ipcRenderer.send('open-user-dir'),
  getDownloadDir: () => ipcRenderer.invoke('get-download-dir'),
  chooseDownloadDir: () => ipcRenderer.invoke('choose-download-dir'),
  resetDownloadDir: () => ipcRenderer.invoke('reset-download-dir'),
  openDownloadDir: () => ipcRenderer.send('open-download-dir'),
  listAssets: () => ipcRenderer.invoke('get-assets'),
  getClipMap: () => ipcRenderer.invoke('get-clip-map'),
  setClipMap: (map) => ipcRenderer.invoke('set-clip-map', map),
  setAudioVolume: (payload) => ipcRenderer.invoke('set-audio-volume', payload),
  setImageHidden: (payload) => ipcRenderer.invoke('set-image-hidden', payload),
  addAudio: (payload) => ipcRenderer.invoke('add-audio', payload),
  addAudioFromUrl: (payload) => ipcRenderer.invoke('add-audio-from-url', payload),
  cancelClip: () => ipcRenderer.send('cancel-clip'),
  clipLocalAudio: (payload) => ipcRenderer.invoke('clip-local-audio', payload),
  confirmAddClip: (payload) => ipcRenderer.invoke('confirm-add-clip', payload),
  discardClip: (payload) => ipcRenderer.invoke('discard-clip', payload),
  retrimClip: (payload) => ipcRenderer.invoke('retrim-clip', payload),
  onClipProgress: (cb) => ipcRenderer.on('clip-progress', cb),
  addImage: (payload) => ipcRenderer.invoke('add-image', payload),
  addImageCutout: (payload) => ipcRenderer.invoke('add-image-cutout', payload),
  deleteAsset: (filePath) => ipcRenderer.invoke('delete-asset', filePath),
  renameAsset: (payload) => ipcRenderer.invoke('rename-asset', payload),
  pathForFile: (file) => webUtils.getPathForFile(file),
  reloadPet: () => ipcRenderer.send('reload-pet'),
  toggleManagerTop: () => ipcRenderer.invoke('toggle-manager-top'),
  getMuted: () => ipcRenderer.invoke('get-muted'),
  toggleMute: () => ipcRenderer.invoke('toggle-mute'),
  onSetMuted: (cb) => ipcRenderer.on('set-muted', cb),
});
